### ISSUE TITLE
Dart 2 runtime cast failures

### ISSUE THREAD

**Issue by srawlins** [google/file.dart#88]
Using a recent dev version of Dart, like 2.0.0-dev.55.0 or so:

```shell
dart --preview-dart-2 test/replay_test.dart
```

See many failures like:

```none
00:00 +3 -6: Replay common FileSystem file rerun allowsDirectoryArgument [E]
  type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' of 'input'
  package:file/src/backends/record_replay/codecs.dart                     _ForwardingConverter.convert
  package:file/src/backends/record_replay/replay_proxy_mixin.dart 134:30  _ReplayFileSystemImpl&FileSystem&ReplayProxyMixin.noSuchMethod
  package:file/src/interface/file_system.dart                             _ReplayFileSystemImpl&FileSystem&ReplayProxyMixin.path
  test/common_tests.dart 134:17                                           runCommonTests.<fn>.ns
```

**Comment by srawlins** [comment]
Partially blocked by https://github.com/dart-lang/sdk/issues/33459.

**Comment by srawlins** [comment]
CC @tvolkert

**Comment by srawlins** [comment]
Specifically this failure:

```
NoSuchMethodError: The method 'encode' was called on null....
NoSuchMethodError: The method 'encode' was called on null.
Receiver: null
Tried calling: encode("foo")
dart:core                                                 Object.noSuchMethod
package:file/src/backends/memory/memory_file.dart 273:33  MemoryFile.writeAsStringSync
package:file/src/backends/memory/memory_file.dart 262:5   MemoryFile.writeAsString
===== asynchronous gap ===========================
dart:async                                                _AsyncAwaitCompleter.completeError
package:file/src/backends/memory/memory_file.dart         MemoryFile.writeAsString
```

is caused by https://github.com/dart-lang/sdk/issues/33459

**Comment by mit-mit** [comment]
Is anyone looking at this? cc @tvolkert

**Comment by tvolkert** [comment]
@srawlins now that dart-lang/sdk#33459 is fixed, can this issue be resolved?

**Comment by srawlins** [comment]
I think it was only partially blocked by dart-lang/sdk#33459. On Dart 2.0.0-dev.69.5 I still get 364 failing tests.

**Comment by pq** [comment]
NP.  Thanks!  Off next week myself but happy to pitch in when I get back.

**Comment by pq** [comment]
w/ 65556d8, we're down to  8 failures and 363 passing tests.
